on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Flake8-Linter:
    runs-on: self-hosted
    name: Flake8
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch Flake8 linter
        uses: actions/checkout@v2
        with:
          repository: betrybe/flake8-linter-action
          ref: v1.3
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/flake8-linter

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '14'

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'master'

      - name: Run Flake8 linter
        id: flake8_linter
        uses: ./.github/actions/flake8-linter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}

  Evaluator:
    runs-on: self-hosted
    name: Evaluator
    needs: [Flake8-Linter]
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch PyTest evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/pytest-evaluator-action
          ref: v5
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/pytest-evaluator

      - name: Fetch Store evaluation
        uses: actions/checkout@v2
        with:
          repository: betrybe/store-evaluation-action
          ref: v4.2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/store-evaluation

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '14'

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'master'

      - name: Run PyTest evaluation
        id: evaluator
        uses: ./.github/actions/pytest-evaluator
        with:
          pr_author_username: ${{ github.event.pull_request.user.login }}

      - name: Run Store evaluation
        uses: ./.github/actions/store-evaluation
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: staging
          pr-number: ${{ github.event.pull_request.number }}
